if(NOT DEFINED SOURCE_ROOT OR NOT IS_ABSOLUTE "${SOURCE_ROOT}")
    message(FATAL_ERROR "SOURCE_ROOT must be an absolute path")
endif()
if(NOT DEFINED RELEASE_VERSION OR RELEASE_VERSION STREQUAL "")
    message(FATAL_ERROR "RELEASE_VERSION is required")
endif()
if(NOT DEFINED RELEASE_TAG OR RELEASE_TAG STREQUAL "")
    message(FATAL_ERROR "RELEASE_TAG is required")
endif()

file(READ "${SOURCE_ROOT}/README.md" readme)
file(READ "${SOURCE_ROOT}/CHANGELOG.md" changelog)
file(READ "${SOURCE_ROOT}/INSTALL.md" install_guide)

set(expected_artifact_pattern "owl-switch-<tag>-macOS-arm64.dmg")
string(FIND "${readme}" "${expected_artifact_pattern}" artifact_pattern_index)
if(artifact_pattern_index EQUAL -1)
    message(FATAL_ERROR "README does not document the OwlSwitch DMG artifact contract")
endif()

string(REGEX REPLACE "^v" "" changelog_release "${RELEASE_TAG}")
string(FIND "${changelog}" "## [${changelog_release}] - " changelog_version_index)
if(changelog_version_index EQUAL -1)
    message(FATAL_ERROR "CHANGELOG has no dated ${changelog_release} section")
endif()

string(FIND "${install_guide}" "onto the Applications shortcut" install_instruction_index)
if(install_instruction_index EQUAL -1)
    message(FATAL_ERROR "INSTALL does not describe the DMG Applications shortcut")
endif()
